matrix:
  - name: Markdown
    aspell:
      lang: en
    dictionary:
      wordlists:
        - .spellcheck_wordlist.txt
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
        markdown_extensions:
          - pymdownx.superfences:
          - pymdownx.highlight:
      - pyspelling.filters.html:
        comments: false
        attributes:
          - title
          - alt
        ignores:
          - code
          - pre
      - pyspelling.filters.url:
    sources:
      - '**/*.md'
    default_encoding: utf-8
