matrix:
- name: Markdown
  sources:
  - '**/*.md'
  aspell:
    lang: en
  dictionary:
    wordlists:
      - .spellcheck_wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.parsers.markdown_parser:
      markdown_extensions:
      - markdown.extensions.toc:
          slugify: !!python/name:pymdownx.slugs.uslugify
          permalink: "\ue157"
      - markdown.extensions.admonition
      - markdown.extensions.smarty
  - pyspelling.filters.html:
    comments: false
    ignores:
    - 'code'
    - 'pre'
  - pyspelling.filters.url:
  default_encoding: utf-8
