name: Linting

on:
  push:
  pull_request:
    branches: 
      - master

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull markdownlint/markdownlint:latest Image
      run: docker pull markdownlint/markdownlint:latest
    - name: Run markdownlint against *.md files
      run: docker run --rm -i -v "$(pwd)":/workdir --workdir /workdir markdownlint/markdownlint:latest $(find . -type f -iname '*.md' | grep -v '/.git/')

# --rules ~MD013,~MD033
      